// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_ComponentView__
#define __javax_swing_text_ComponentView__

#pragma interface

#include <javax/swing/text/View.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Graphics;
      class Shape;
      class Component;
    }
  }
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
        class ComponentView;
        class View;
        class Position$Bias;
        class Element;
      }
    }
  }
}

class javax::swing::text::ComponentView : public ::javax::swing::text::View
{
public:
  ComponentView (::javax::swing::text::Element *);
public:  // actually protected
  virtual ::java::awt::Component *createComponent () { return 0; }
public:
  virtual jfloat getAlignment (jint);
  ::java::awt::Component *getComponent () { return 0; }
  virtual jfloat getMaximumSpan (jint);
  virtual jfloat getMinimumSpan (jint);
  virtual jfloat getPreferredSpan (jint);
  virtual ::java::awt::Shape *modelToView (jint, ::java::awt::Shape *, ::javax::swing::text::Position$Bias *) { return 0; }
  virtual void paint (::java::awt::Graphics *, ::java::awt::Shape *) { }
  virtual void setParent (::javax::swing::text::View *) { }
  virtual void setSize (jfloat, jfloat) { }
  virtual jint viewToModel (jfloat, jfloat, ::java::awt::Shape *, JArray< ::javax::swing::text::Position$Bias *> *);

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_text_ComponentView__ */
