// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_DocumentFilter__
#define __javax_swing_text_DocumentFilter__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
        class DocumentFilter;
      }
    }
  }
}

class javax::swing::text::DocumentFilter : public ::java::lang::Object
{
public:
  DocumentFilter ();

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_text_DocumentFilter__ */
