// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_NavigationFilter__
#define __javax_swing_text_NavigationFilter__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
        class NavigationFilter;
      }
    }
  }
}

class javax::swing::text::NavigationFilter : public ::java::lang::Object
{
public:
  NavigationFilter ();

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_text_NavigationFilter__ */
