// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_awt_image_SinglePixelPackedSampleModel__
#define __java_awt_image_SinglePixelPackedSampleModel__

#pragma interface

#include <java/awt/image/SampleModel.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      namespace image
      {
        class SinglePixelPackedSampleModel;
        class DataBuffer;
        class SampleModel;
      }
    }
  }
}

class java::awt::image::SinglePixelPackedSampleModel : public ::java::awt::image::SampleModel
{
public:
  SinglePixelPackedSampleModel (jint, jint, jint, jintArray);
  SinglePixelPackedSampleModel (jint, jint, jint, jint, jintArray);
  virtual jint getNumDataElements ();
  virtual ::java::awt::image::SampleModel *createCompatibleSampleModel (jint, jint);
  virtual ::java::awt::image::DataBuffer *createDataBuffer ();
  virtual jintArray getSampleSize () { return sampleSize; }
  virtual jint getSampleSize (jint);
  virtual jint getOffset (jint, jint);
  virtual jintArray getBitOffsets () { return bitOffsets; }
  virtual jintArray getBitMasks () { return bitMasks; }
  virtual jint getScanlineStride () { return scanlineStride; }
  virtual ::java::awt::image::SampleModel *createSubsetSampleModel (jintArray);
  virtual ::java::lang::Object *getDataElements (jint, jint, ::java::lang::Object *, ::java::awt::image::DataBuffer *);
  virtual jintArray getPixel (jint, jint, jintArray, ::java::awt::image::DataBuffer *);
  virtual jintArray getPixels (jint, jint, jint, jint, jintArray, ::java::awt::image::DataBuffer *);
  virtual jint getSample (jint, jint, jint, ::java::awt::image::DataBuffer *);
  virtual void setDataElements (jint, jint, ::java::lang::Object *, ::java::awt::image::DataBuffer *);
  virtual void setPixel (jint, jint, jintArray, ::java::awt::image::DataBuffer *);
  virtual void setSample (jint, jint, jint, jint, ::java::awt::image::DataBuffer *);
private:
  jint __attribute__((aligned(__alignof__( ::java::awt::image::SampleModel ))))  scanlineStride;
  jintArray bitMasks;
  jintArray bitOffsets;
  jintArray sampleSize;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_awt_image_SinglePixelPackedSampleModel__ */
