// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_accessibility_AccessibleHypertext__
#define __javax_accessibility_AccessibleHypertext__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace accessibility
    {
      class AccessibleHypertext;
      class AccessibleHyperlink;
    }
  }
}

class javax::accessibility::AccessibleHypertext : public ::java::lang::Object
{
public:
  virtual jint getLinkCount () = 0;
  virtual ::javax::accessibility::AccessibleHyperlink *getLink (jint) = 0;
  virtual jint getLinkIndex (jint) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_accessibility_AccessibleHypertext__ */
