// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_awt_peer_FileDialogPeer__
#define __java_awt_peer_FileDialogPeer__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      namespace peer
      {
        class FileDialogPeer;
      }
    }
  }
}

class java::awt::peer::FileDialogPeer : public ::java::lang::Object
{
public:
  virtual void setFile (::java::lang::String *) = 0;
  virtual void setDirectory (::java::lang::String *) = 0;
  virtual void setFilenameFilter (::java::io::FilenameFilter *) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __java_awt_peer_FileDialogPeer__ */
