// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_awt_peer_MenuPeer__
#define __java_awt_peer_MenuPeer__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      namespace peer
      {
        class MenuPeer;
      }
      class MenuItem;
    }
  }
}

class java::awt::peer::MenuPeer : public ::java::lang::Object
{
public:
  virtual void addItem (::java::awt::MenuItem *) = 0;
  virtual void addSeparator () = 0;
  virtual void delItem (jint) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __java_awt_peer_MenuPeer__ */
