// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicLookAndFeel__
#define __javax_swing_plaf_basic_BasicLookAndFeel__

#pragma interface

#include <javax/swing/LookAndFeel.h>
#include <gcj/array.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace plaf
      {
        namespace basic
        {
          class BasicLookAndFeel;
        }
      }
      class UIDefaults;
    }
  }
}

class javax::swing::plaf::basic::BasicLookAndFeel : public ::javax::swing::LookAndFeel
{
public:
  BasicLookAndFeel ();
  virtual ::javax::swing::UIDefaults *getDefaults ();
public:  // actually protected
  virtual void initClassDefaults (::javax::swing::UIDefaults *);
  virtual void initSystemColorDefaults (::javax::swing::UIDefaults *);
  virtual void loadSystemColors (::javax::swing::UIDefaults *, JArray< ::java::lang::String *> *, jboolean) { }
private:
  void loadResourceBundle (::javax::swing::UIDefaults *);
public:  // actually protected
  virtual void initComponentDefaults (::javax::swing::UIDefaults *);
public: // actually package-private
  static const jlong serialVersionUID = -6096995660290287879LL;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicLookAndFeel__ */
