// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicLabelUI__
#define __javax_swing_plaf_basic_BasicLabelUI__

#pragma interface

#include <javax/swing/plaf/LabelUI.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace plaf
      {
        namespace basic
        {
          class BasicLabelUI;
        }
        class ComponentUI;
      }
      class JComponent;
    }
  }
  namespace java
  {
    namespace beans
    {
      class PropertyChangeEvent;
    }
    namespace awt
    {
      class Rectangle;
      class Graphics;
      class Dimension;
      class Color;
    }
  }
}

class javax::swing::plaf::basic::BasicLabelUI : public ::javax::swing::plaf::LabelUI
{
public:
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
  virtual void installUI (::javax::swing::JComponent *);
  virtual ::java::awt::Dimension *getPreferredSize (::javax::swing::JComponent *);
  virtual void paint (::java::awt::Graphics *, ::javax::swing::JComponent *);
public:  // actually protected
  virtual void paintFocus (::java::awt::Graphics *, ::javax::swing::JComponent *, ::java::awt::Rectangle *, ::java::awt::Rectangle *, ::java::awt::Rectangle *) { }
  virtual void paintIcon (::java::awt::Graphics *, ::javax::swing::JComponent *, ::java::awt::Rectangle *);
  virtual void paintText (::java::awt::Graphics *, ::javax::swing::JComponent *, ::java::awt::Rectangle *, ::java::lang::String *);
public:
  virtual void propertyChange (::java::beans::PropertyChangeEvent *);
  BasicLabelUI ();
public: // actually package-private
  jint __attribute__((aligned(__alignof__( ::javax::swing::plaf::LabelUI ))))  gap;
  ::java::awt::Color *foreground;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicLabelUI__ */
