// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicTabbedPaneUI__
#define __javax_swing_plaf_basic_BasicTabbedPaneUI__

#pragma interface

#include <javax/swing/plaf/TabbedPaneUI.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Rectangle;
      class Dimension;
    }
  }
  namespace javax
  {
    namespace swing
    {
      class JTabbedPane;
      namespace plaf
      {
        namespace basic
        {
          class BasicTabbedPaneUI;
        }
        class ComponentUI;
      }
      class JComponent;
    }
  }
}

class javax::swing::plaf::basic::BasicTabbedPaneUI : public ::javax::swing::plaf::TabbedPaneUI
{
public:
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
  virtual void installUI (::javax::swing::JComponent *);
  virtual ::java::awt::Dimension *getPreferredSize (::javax::swing::JComponent *);
  virtual ::java::awt::Rectangle *getTabBounds (::javax::swing::JTabbedPane *, jint) { return 0; }
  virtual jint getTabRunCount (::javax::swing::JTabbedPane *);
  virtual jint tabForCoordinate (::javax::swing::JTabbedPane *, jint, jint);
  BasicTabbedPaneUI ();

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicTabbedPaneUI__ */
