// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_basic_BasicScrollPaneUI__
#define __javax_swing_plaf_basic_BasicScrollPaneUI__

#pragma interface

#include <javax/swing/plaf/ScrollPaneUI.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Graphics;
      class Dimension;
    }
  }
  namespace javax
  {
    namespace swing
    {
      namespace plaf
      {
        namespace basic
        {
          class BasicScrollPaneUI;
        }
        class ComponentUI;
      }
      class JComponent;
    }
  }
}

class javax::swing::plaf::basic::BasicScrollPaneUI : public ::javax::swing::plaf::ScrollPaneUI
{
public:
  static ::javax::swing::plaf::ComponentUI *createUI (::javax::swing::JComponent *);
  virtual void installUI (::javax::swing::JComponent *);
  virtual ::java::awt::Dimension *getPreferredSize (::javax::swing::JComponent *);
  virtual void paint (::java::awt::Graphics *, ::javax::swing::JComponent *);
  BasicScrollPaneUI ();
public: // actually package-private
  jint __attribute__((aligned(__alignof__( ::javax::swing::plaf::ScrollPaneUI ))))  min_w;
  jint min_h;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_plaf_basic_BasicScrollPaneUI__ */
