// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_nio_charset_CharacterCodingException__
#define __java_nio_charset_CharacterCodingException__

#pragma interface

#include <java/io/IOException.h>

extern "Java"
{
  namespace java
  {
    namespace nio
    {
      namespace charset
      {
        class CharacterCodingException;
      }
    }
  }
}

class java::nio::charset::CharacterCodingException : public ::java::io::IOException
{
public:
  CharacterCodingException ();

  static ::java::lang::Class class$;
};

#endif /* __java_nio_charset_CharacterCodingException__ */
