/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Linux/arm 3.2.40 Kernel Configuration
 *
 */
#ifndef __SYNO_AUTOCONF_H__
#define __SYNO_AUTOCONF_H__
#define CONFIG_SYNO_MTD_PHYMAPS 1
#define CONFIG_SYNO_BTRFS_QGROUP_QUERY 1
#define CONFIG_BTRFS_FS_SYNO_USRQUOTA 1
#define CONFIG_SYNO_ARMADA_ARCH_V2 1
#define CONFIG_SYNO_NOTIFY 1
#define CONFIG_SYNO_DISPLAY_CPUINFO 1
#define CONFIG_BTRFS_FS_SYNO_ACL 1
#define CONFIG_SYNO_ARMADA_ARCH_COMM 1
#define CONFIG_SYNO_ARMADA_V2 1
#define CONFIG_SYNO_FORCE_EH_FULL_RECOVER_RETRY 1
#define CONFIG_SYNO_FIX_OCF_CRYPTODEV_RACE 1
#define CONFIG_EXT4_FS_SYNO_ACL 1
#define CONFIG_SYNO_FIX_OCF_CRYPTOSOFT_RACE 1
#define CONFIG_SYNO_ARMADAXP_CPU_AFFINITY 1
#define CONFIG_FS_SYNO_ACL 1
#define CONFIG_SYNO_USE_OCF_LINUX 1
#endif /* __SYNO_AUTOCONF_H__ */