// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_event_ListDataListener__
#define __javax_swing_event_ListDataListener__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace event
      {
        class ListDataListener;
        class ListDataEvent;
      }
    }
  }
}

class javax::swing::event::ListDataListener : public ::java::lang::Object
{
public:
  virtual void contentsChanged (::javax::swing::event::ListDataEvent *) = 0;
  virtual void intervalAdded (::javax::swing::event::ListDataEvent *) = 0;
  virtual void intervalRemoved (::javax::swing::event::ListDataEvent *) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_swing_event_ListDataListener__ */
