// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_security_provider_GnuDSAPublicKey__
#define __gnu_java_security_provider_GnuDSAPublicKey__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace security
      {
        namespace provider
        {
          class GnuDSAPublicKey;
        }
      }
    }
  }
  namespace java
  {
    namespace security
    {
      namespace interfaces
      {
        class DSAParams;
      }
    }
    namespace math
    {
      class BigInteger;
    }
  }
}

class gnu::java::security::provider::GnuDSAPublicKey : public ::java::lang::Object
{
public:
  GnuDSAPublicKey (::java::math::BigInteger *, ::java::math::BigInteger *, ::java::math::BigInteger *, ::java::math::BigInteger *);
  virtual ::java::lang::String *getAlgorithm ();
  virtual ::java::lang::String *getFormat () { return 0; }
  virtual jbyteArray getEncoded () { return 0; }
  virtual ::java::security::interfaces::DSAParams *getParams ();
  virtual ::java::math::BigInteger *getY () { return y; }
  virtual ::java::lang::String *toString ();
public: // actually package-private
  ::java::math::BigInteger * __attribute__((aligned(__alignof__( ::java::lang::Object )))) y;
  ::java::math::BigInteger *p;
  ::java::math::BigInteger *q;
  ::java::math::BigInteger *g;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_security_provider_GnuDSAPublicKey__ */
