// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_awt_Canvas__
#define __java_awt_Canvas__

#pragma interface

#include <java/awt/Component.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Canvas;
      class Graphics;
      class GraphicsConfiguration;
    }
  }
}

class java::awt::Canvas : public ::java::awt::Component
{
public:
  Canvas ();
  Canvas (::java::awt::GraphicsConfiguration *);
public: // actually package-private
  virtual ::java::awt::GraphicsConfiguration *getGraphicsConfigurationImpl ();
public:
  virtual void addNotify ();
  virtual void paint (::java::awt::Graphics *);
public: // actually package-private
  ::java::awt::GraphicsConfiguration * __attribute__((aligned(__alignof__( ::java::awt::Component )))) graphicsConfiguration;
private:
  static const jlong serialVersionUID = -2284879212465893870LL;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_awt_Canvas__ */
