// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_net_protocol_jar_Connection__
#define __gnu_java_net_protocol_jar_Connection__

#pragma interface

#include <java/net/JarURLConnection.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace net
      {
        namespace protocol
        {
          namespace jar
          {
            class Connection;
          }
        }
      }
    }
  }
  namespace java
  {
    namespace net
    {
      class URL;
    }
  }
}

class gnu::java::net::protocol::jar::Connection : public ::java::net::JarURLConnection
{
public:  // actually protected
  Connection (::java::net::URL *);
public:
  void connect ();
  ::java::io::InputStream *getInputStream ();
  ::java::util::jar::JarFile *getJarFile ();
  ::java::lang::String *getHeaderField (::java::lang::String *);
  ::java::util::Map *getHeaderFields ();
  ::java::lang::String *getHeaderField (jint);
  ::java::lang::String *getHeaderFieldKey (jint);
private:
  ::java::lang::String *getKey (::java::lang::String *);
  ::java::lang::String *getField (::java::lang::String *);
  void getHeaders ();
  static ::java::util::Hashtable *file_cache;
  ::java::util::jar::JarFile * __attribute__((aligned(__alignof__( ::java::net::JarURLConnection )))) jar_file;
public: // actually package-private
  static ::java::util::HashMap *connectionCache;
private:
  ::java::util::Hashtable *hdrHash;
  ::java::util::Vector *hdrVec;
  jboolean gotHeaders;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_net_protocol_jar_Connection__ */
