/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.13.1
 * Thu May 29 01:39:54 2008
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MIPS 1
#undef CONFIG_MIPS64
#undef CONFIG_64BIT
#define CONFIG_MIPS32 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_BROKEN_ON_SMP 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION "-ohio"
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#undef CONFIG_POSIX_MQUEUE
#undef CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#undef CONFIG_IKCONFIG
#define CONFIG_EMBEDDED 1
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_ALL
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#undef CONFIG_BASE_FULL
#undef CONFIG_FUTEX
#define CONFIG_EPOLL 1
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1
#undef CONFIG_SHMEM
#define CONFIG_CC_ALIGN_FUNCTIONS 4
#define CONFIG_CC_ALIGN_LABELS 4
#define CONFIG_CC_ALIGN_LOOPS 4
#define CONFIG_CC_ALIGN_JUMPS 4
#define CONFIG_TINY_SHMEM 1
#define CONFIG_BASE_SMALL 1

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#undef CONFIG_MODULE_FORCE_UNLOAD
#define CONFIG_OBSOLETE_MODPARM 1
#undef CONFIG_MODVERSIONS
#undef CONFIG_MODULE_SRCVERSION_ALL
#undef CONFIG_KMOD

/*
 * Machine selection
 */
#undef CONFIG_MACH_JAZZ
#undef CONFIG_MACH_VR41XX
#undef CONFIG_TOSHIBA_JMR3927
#undef CONFIG_MIPS_COBALT
#undef CONFIG_MACH_DECSTATION
#undef CONFIG_MIPS_EV64120
#undef CONFIG_MIPS_EV96100
#undef CONFIG_MIPS_IVR
#undef CONFIG_LASAT
#undef CONFIG_MIPS_ITE8172
#undef CONFIG_MIPS_ATLAS
#undef CONFIG_MIPS_MALTA
#undef CONFIG_MIPS_SEAD
#define CONFIG_MIPS_OHIO 1
#undef CONFIG_MIPS_AR7
#undef CONFIG_MIPS_UR8
#define CONFIG_MIPS_OHIO_PHY_MEMSTART 0x14000000
#define CONFIG_OHIO_CLOCK_SWITCH 1
#undef CONFIG_AVM_SIMPLE_PROFILING
#define CONFIG_DISABLE_OOM_KILLER 1
#define CONFIG_VLYNQ_SUPPORT 1
#define CONFIG_VLYNQ_SUPPORT_CLK 62500000
#define CONFIG_GPIO_SSI 1
#define CONFIG_GPIO_SSI_CS 8
#define CONFIG_GPIO_SSI_CS2 11
#define CONFIG_GPIO_SSI_CS3 3
#define CONFIG_GPIO_SSI_CLK 4
#define CONFIG_GPIO_SSI_DATA 5
#undef CONFIG_MOMENCO_OCELOT
#undef CONFIG_MOMENCO_OCELOT_G
#undef CONFIG_MOMENCO_OCELOT_C
#undef CONFIG_MOMENCO_OCELOT_3
#undef CONFIG_MOMENCO_JAGUAR_ATX
#undef CONFIG_DDB5074
#undef CONFIG_DDB5476
#undef CONFIG_DDB5477
#undef CONFIG_NEC_OSPREY
#undef CONFIG_SGI_IP22
#undef CONFIG_SOC_AU1X00
#undef CONFIG_SIBYTE_SB1xxx_SOC
#undef CONFIG_SNI_RM200_PCI
#undef CONFIG_TOSHIBA_RBTX4927
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_HAVE_DEC_LOCK 1
#define CONFIG_DMA_NONCOHERENT 1
#define CONFIG_CPU_LITTLE_ENDIAN 1
#define CONFIG_MIPS_BOARDS_GEN 1
#define CONFIG_MIPS_L1_CACHE_SHIFT 5

/*
 * CPU selection
 */
#define CONFIG_CPU_MIPS32 1
#undef CONFIG_CPU_MIPS64
#undef CONFIG_CPU_R3000
#undef CONFIG_CPU_TX39XX
#undef CONFIG_CPU_VR41XX
#undef CONFIG_CPU_R4300
#undef CONFIG_CPU_R4X00
#undef CONFIG_CPU_TX49XX
#undef CONFIG_CPU_R5000
#undef CONFIG_CPU_R5432
#undef CONFIG_CPU_R6000
#undef CONFIG_CPU_NEVADA
#undef CONFIG_CPU_R8000
#undef CONFIG_CPU_R10000
#undef CONFIG_CPU_RM7000
#undef CONFIG_CPU_RM9000
#undef CONFIG_CPU_SB1
#define CONFIG_PAGE_SIZE_4KB 1
#undef CONFIG_PAGE_SIZE_8KB
#undef CONFIG_PAGE_SIZE_16KB
#undef CONFIG_PAGE_SIZE_64KB
#define CONFIG_CPU_HAS_PREFETCH 1
#undef CONFIG_VTAG_ICACHE
#undef CONFIG_64BIT_PHYS_ADDR
#undef CONFIG_CPU_ADVANCED
#define CONFIG_CPU_HAS_LLSC 1
#define CONFIG_CPU_HAS_SYNC 1
#define CONFIG_ARCH_FLATMEM_ENABLE 1
#define CONFIG_SELECT_MEMORY_MODEL 1
#define CONFIG_FLATMEM_MANUAL 1
#undef CONFIG_DISCONTIGMEM_MANUAL
#undef CONFIG_SPARSEMEM_MANUAL
#define CONFIG_FLATMEM 1
#define CONFIG_FLAT_NODE_MEM_MAP 1
#undef CONFIG_PREEMPT

/*
 * Bus options (PCI, PCMCIA, EISA, ISA, TC)
 */
#define CONFIG_MMU 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#undef CONFIG_PCCARD

/*
 * PCI Hotplug Support
 */

/*
 * Executable file formats
 */
#define CONFIG_BINFMT_ELF 1
#undef CONFIG_BINFMT_MISC
#define CONFIG_TRAD_SIGNALS 1

/*
 * Networking
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#define CONFIG_UNIX 1
#undef CONFIG_NET_KEY
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#undef CONFIG_IP_ADVANCED_ROUTER
#define CONFIG_IP_FIB_HASH 1
#define CONFIG_IP_PNP 1
#define CONFIG_IP_PNP_DHCP 1
#define CONFIG_IP_PNP_BOOTP 1
#define CONFIG_IP_PNP_RARP 1
#undef CONFIG_NET_IPIP
#undef CONFIG_NET_IPGRE
#define CONFIG_IP_MROUTE 1
#define CONFIG_IP_PIMSM_V1 1
#define CONFIG_IP_PIMSM_V2 1
#undef CONFIG_ARPD
#undef CONFIG_SYN_COOKIES
#undef CONFIG_INET_AH
#undef CONFIG_INET_ESP
#undef CONFIG_INET_IPCOMP
#undef CONFIG_INET_TUNNEL
#undef CONFIG_IP_TCPDIAG
#undef CONFIG_IP_TCPDIAG_IPV6
#undef CONFIG_TCP_CONG_ADVANCED
#define CONFIG_TCP_CONG_BIC 1

/*
 * IP: Virtual Server Configuration
 */
#undef CONFIG_IP_VS
#define CONFIG_IP_MULTICAST_FASTFORWARD 1
#undef CONFIG_IPV6
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#undef CONFIG_BRIDGE_NETFILTER

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_CT_ACCT 1
#define CONFIG_IP_NF_CONNTRACK_MARK 1
#define CONFIG_IP_NF_CT_PROTO_SCTP_MODULE 1
#define CONFIG_IP_NF_FTP_MODULE 1
#define CONFIG_IP_NF_IRC_MODULE 1
#define CONFIG_IP_NF_TFTP_MODULE 1
#define CONFIG_IP_NF_AMANDA_MODULE 1
#define CONFIG_IP_NF_QUEUE 1
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP_NF_MATCH_IPRANGE_MODULE 1
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP_NF_MATCH_PKTTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#define CONFIG_IP_NF_MATCH_RECENT_MODULE 1
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#define CONFIG_IP_NF_MATCH_DSCP_MODULE 1
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#define CONFIG_IP_NF_MATCH_HELPER_MODULE 1
#define CONFIG_IP_NF_MATCH_STATE_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP_NF_MATCH_ADDRTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_REALM_MODULE 1
#define CONFIG_IP_NF_MATCH_SCTP_MODULE 1
#define CONFIG_IP_NF_MATCH_COMMENT_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNMARK_MODULE 1
#define CONFIG_IP_NF_MATCH_HASHLIMIT_MODULE 1
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#define CONFIG_IP_NF_TARGET_TCPMSS_MODULE 1
#define CONFIG_IP_NF_NAT_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE_MODULE 1
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#define CONFIG_IP_NF_TARGET_NETMAP_MODULE 1
#define CONFIG_IP_NF_TARGET_SAME_MODULE 1
#undef CONFIG_IP_NF_NAT_SNMP_BASIC
#define CONFIG_IP_NF_NAT_IRC_MODULE 1
#define CONFIG_IP_NF_NAT_FTP_MODULE 1
#define CONFIG_IP_NF_NAT_TFTP_MODULE 1
#define CONFIG_IP_NF_NAT_AMANDA_MODULE 1
#define CONFIG_IP_NF_MANGLE_MODULE 1
#define CONFIG_IP_NF_TARGET_TOS_MODULE 1
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#undef CONFIG_IP_NF_TARGET_DSCP
#define CONFIG_IP_NF_TARGET_MARK_MODULE 1
#undef CONFIG_IP_NF_TARGET_CLASSIFY
#undef CONFIG_IP_NF_TARGET_CONNMARK
#undef CONFIG_IP_NF_TARGET_CLUSTERIP
#define CONFIG_IP_NF_RAW_MODULE 1
#undef CONFIG_IP_NF_TARGET_NOTRACK
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#undef CONFIG_IP_NF_ARPFILTER
#undef CONFIG_IP_NF_ARP_MANGLE

/*
 * Bridge: Netfilter Configuration
 */
#undef CONFIG_BRIDGE_NF_EBTABLES

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_SCTP
#define CONFIG_ATM 1
#undef CONFIG_ATM_CLIP
#undef CONFIG_ATM_LANE
#define CONFIG_ATM_BR2684 1
#define CONFIG_ATM_BR2684_IPFILTER 1
#define CONFIG_BRIDGE 1
#define CONFIG_VLAN_8021Q 1
#undef CONFIG_DECNET
#undef CONFIG_LLC2
#undef CONFIG_IPX
#undef CONFIG_ATALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#undef CONFIG_NET_DIVERT
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER
#define CONFIG_NET_SCHED 1
#undef CONFIG_NET_SCH_CLK_JIFFIES
#undef CONFIG_NET_SCH_CLK_GETTIMEOFDAY
#define CONFIG_NET_SCH_CLK_CPU 1
#define CONFIG_NET_SCH_CBQ_MODULE 1
#define CONFIG_NET_SCH_HTB_MODULE 1
#define CONFIG_NET_SCH_HFSC_MODULE 1
#define CONFIG_NET_SCH_ATM_MODULE 1
#define CONFIG_NET_SCH_PRIO_MODULE 1
#undef CONFIG_NET_SCH_RED
#define CONFIG_NET_SCH_SFQ_MODULE 1
#undef CONFIG_NET_SCH_TEQL
#define CONFIG_NET_SCH_TBF_MODULE 1
#undef CONFIG_NET_SCH_GRED
#undef CONFIG_NET_SCH_DSMARK
#undef CONFIG_NET_SCH_NETEM
#define CONFIG_NET_SCH_LLQ_MODULE 1
#undef CONFIG_NET_SCH_INGRESS
#define CONFIG_NET_QOS 1
#define CONFIG_NET_ESTIMATOR 1
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_BASIC_MODULE 1
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#undef CONFIG_NET_CLS_ROUTE4
#define CONFIG_NET_CLS_ROUTE 1
#undef CONFIG_NET_CLS_FW
#define CONFIG_NET_CLS_U32_MODULE 1
#undef CONFIG_CLS_U32_PERF
#undef CONFIG_NET_CLS_IND
#undef CONFIG_CLS_U32_MARK
#undef CONFIG_NET_CLS_RSVP
#undef CONFIG_NET_CLS_RSVP6
#undef CONFIG_NET_EMATCH
#undef CONFIG_NET_CLS_ACT
#undef CONFIG_NET_CLS_POLICE

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#undef CONFIG_HAMRADIO
#undef CONFIG_IRDA
#define CONFIG_BT_MODULE 1
#define CONFIG_BT_L2CAP_MODULE 1
#undef CONFIG_BT_SCO
#define CONFIG_BT_RFCOMM_MODULE 1
#define CONFIG_BT_RFCOMM_TTY 1
#define CONFIG_BT_BNEP_MODULE 1
#define CONFIG_BT_BNEP_MC_FILTER 1
#define CONFIG_BT_BNEP_PROTO_FILTER 1
#undef CONFIG_BT_CMTP
#undef CONFIG_BT_HIDP

/*
 * Bluetooth device drivers
 */
#define CONFIG_BT_HCIUSB_MODULE 1
#define CONFIG_BT_HCIUSB_SCO 1
#undef CONFIG_BT_HCIUART
#undef CONFIG_BT_HCIBCM203X
#undef CONFIG_BT_HCIBPA10X
#undef CONFIG_BT_HCIBFUSB
#undef CONFIG_BT_HCIVHCI

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#undef CONFIG_FW_LOADER
#undef CONFIG_DEBUG_DRIVER

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD 1
#undef CONFIG_MTD_DEBUG
#undef CONFIG_MTD_CONCAT
#define CONFIG_MTD_PARTITIONS 1
#undef CONFIG_MTD_REDBOOT_PARTS
#define CONFIG_MTD_CMDLINE_PARTS 1

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR 1
#define CONFIG_MTD_BLOCK 1
#undef CONFIG_FTL
#undef CONFIG_NFTL
#undef CONFIG_INFTL

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI 1
#undef CONFIG_MTD_SPI
#define CONFIG_MTD_JEDECPROBE 1
#define CONFIG_MTD_GEN_PROBE 1
#define CONFIG_MTD_CFI_ADV_OPTIONS 1
#define CONFIG_MTD_CFI_NOSWAP 1
#undef CONFIG_MTD_CFI_BE_BYTE_SWAP
#undef CONFIG_MTD_CFI_LE_BYTE_SWAP
#define CONFIG_MTD_CFI_GEOMETRY 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_4
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#undef CONFIG_MTD_CFI_I2
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#undef CONFIG_MTD_OTP
#define CONFIG_MTD_CFI_INTELEXT 1
#define CONFIG_MTD_CFI_AMDSTD 1
#define CONFIG_MTD_CFI_AMDSTD_RETRY 0
#undef CONFIG_MTD_CFI_STAA
#define CONFIG_MTD_CFI_UTIL 1
#define CONFIG_MTD_RAM 1
#undef CONFIG_MTD_ROM
#undef CONFIG_MTD_ABSENT

/*
 * Mapping drivers for chip access
 */
#undef CONFIG_MTD_COMPLEX_MAPPINGS
#define CONFIG_MTD_PHYSMAP 1
#define CONFIG_MTD_PHYSMAP_START 0x10000000
#define CONFIG_MTD_PHYSMAP_LEN 0x400000
#define CONFIG_MTD_PHYSMAP_BANKWIDTH 2
#undef CONFIG_MTD_CSTM_MIPS_IXX
#define CONFIG_MTD_OHIO 1
#define CONFIG_MTD_PLATRAM 1

/*
 * Self-contained MTD device drivers
 */
#undef CONFIG_MTD_SLRAM
#undef CONFIG_MTD_PHRAM
#undef CONFIG_MTD_MTDRAM
#undef CONFIG_MTD_BLKMTD
#undef CONFIG_MTD_BLOCK2MTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef CONFIG_MTD_DOC2000
#undef CONFIG_MTD_DOC2001
#undef CONFIG_MTD_DOC2001PLUS

/*
 * NAND Flash Device Drivers
 */
#define CONFIG_MTD_NAND_MODULE 1
#undef CONFIG_MTD_NAND_VERIFY_WRITE
#define CONFIG_MTD_NAND_OHIO_MODULE 1
#define CONFIG_MTD_NAND_IDS_MODULE 1
#undef CONFIG_MTD_NAND_DISKONCHIP
#undef CONFIG_MTD_NAND_NANDSIM

/*
 * Parallel port support
 */
#undef CONFIG_PARPORT

/*
 * Plug and Play support
 */

/*
 * Block devices
 */
#undef CONFIG_BLK_DEV_FD
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP_MODULE 1
#undef CONFIG_BLK_DEV_CRYPTOLOOP
#define CONFIG_BLK_DEV_NBD_MODULE 1
#undef CONFIG_BLK_DEV_UB
#undef CONFIG_BLK_DEV_RAM
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_LBD
#undef CONFIG_CDROM_PKTCDVD

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#undef CONFIG_IOSCHED_AS
#undef CONFIG_IOSCHED_DEADLINE
#undef CONFIG_IOSCHED_CFQ
#undef CONFIG_ATA_OVER_ETH

/*
 * ATA/ATAPI/MFM/RLL support
 */
#undef CONFIG_IDE

/*
 * SCSI device support
 */
#define CONFIG_SCSI_MODULE 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD_MODULE 1
#undef CONFIG_CHR_DEV_ST
#undef CONFIG_CHR_DEV_OSST
#define CONFIG_BLK_DEV_SR_MODULE 1
#undef CONFIG_BLK_DEV_SR_VENDOR
#define CONFIG_CHR_DEV_SG_MODULE 1
#undef CONFIG_CHR_DEV_SCH

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#define CONFIG_SCSI_MULTI_LUN 1
#undef CONFIG_SCSI_CONSTANTS
#undef CONFIG_SCSI_LOGGING

/*
 * SCSI Transport Attributes
 */
#undef CONFIG_SCSI_SPI_ATTRS
#undef CONFIG_SCSI_FC_ATTRS
#undef CONFIG_SCSI_ISCSI_ATTRS

/*
 * SCSI low-level drivers
 */
#undef CONFIG_SCSI_SATA
#undef CONFIG_SCSI_DEBUG

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#undef CONFIG_BLK_DEV_MD
#define CONFIG_BLK_DEV_DM_MODULE 1
#define CONFIG_DM_CRYPT_MODULE 1
#undef CONFIG_DM_SNAPSHOT
#undef CONFIG_DM_MIRROR
#undef CONFIG_DM_ZERO
#undef CONFIG_DM_MULTIPATH

/*
 * Fusion MPT device support
 */
#undef CONFIG_FUSION

/*
 * IEEE 1394 (FireWire) support
 */

/*
 * I2O device support
 */

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#undef CONFIG_BONDING
#undef CONFIG_EQUALIZER
#define CONFIG_TUN 1

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#undef CONFIG_MII
#undef CONFIG_TI_DAVINCI_EMAC
#undef CONFIG_MIPS_AVALANCHE_USB
#define CONFIG_AVM_CPMAC 1
#define CONFIG_AVM_CPMAC_NUM_RX_BUFFERS 256
#define CONFIG_AVM_CPMAC_SWITCH 1

/*
 * Ethernet (1000 Mbit)
 */

/*
 * Ethernet (10000 Mbit)
 */

/*
 * Token Ring devices
 */

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1

/*
 * Obsolete Wireless cards support (pre-802.11)
 */
#undef CONFIG_STRIP
#undef CONFIG_ATMEL

/*
 * AVM WLAN AP support
 */
#define CONFIG_AVM_WLAN_MODULE 1

/*
 * Wan interfaces
 */
#undef CONFIG_WAN

/*
 * ATM drivers
 */
#undef CONFIG_ATM_TCP
#undef CONFIG_ATM_AVM

/*
 * VDSL2 drivers
 */
#define CONFIG_VINAX_MODULE 1
#define CONFIG_PPP_MODULE 1
#define CONFIG_PPP_MULTILINK 1
#undef CONFIG_PPP_FILTER
#define CONFIG_PPP_ASYNC_MODULE 1
#undef CONFIG_PPP_SYNC_TTY
#define CONFIG_PPP_DEFLATE_MODULE 1
#undef CONFIG_PPP_BSDCOMP
#define CONFIG_PPP_MPPE_MPPC_MODULE 1
#undef CONFIG_PPPOE
#undef CONFIG_PPPOATM
#undef CONFIG_SLIP
#undef CONFIG_SHAPER
#undef CONFIG_NETCONSOLE
#undef CONFIG_NETPOLL
#undef CONFIG_NET_POLL_CONTROLLER
#define CONFIG_REMOTE_FRITZ_CONTROL_MODULE 1

/*
 * ISDN subsystem
 */
#define CONFIG_ISDN 1

/*
 * Old ISDN4Linux
 */
#undef CONFIG_ISDN_I4L

/*
 * CAPI subsystem
 */
#define CONFIG_ISDN_CAPI 1
#define CONFIG_CAPI_OSLIB 1
#undef CONFIG_CAPI_OSLIB_DEBUG
#define CONFIG_CAPI_CODEC_MODULE 1
#undef CONFIG_CAPI_CODEC_SPEEX
#undef CONFIG_CAPI_CODEC_ILBC
#undef CONFIG_CAPI_CODEC_G729
#define CONFIG_CAPI_CODEC_FAX 1
#undef CONFIG_CAPI_CODEC_G711
#undef CONFIG_CAPI_CODEC_G722
#undef CONFIG_CAPI_CODEC_G726
#undef CONFIG_CAPI_CODEC_VAD
#undef CONFIG_CAPI_CODEC_CNG
#undef CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON
#undef CONFIG_ISDN_CAPI_MIDDLEWARE
#undef CONFIG_ISDN_CAPI_CAPI20

/*
 * CAPI hardware drivers
 */

/*
 * Active AVM cards
 */
#define CONFIG_CAPI_AVM 1
#undef CONFIG_ISDN_DRV_AVMB1_B1PCMCIA
#undef CONFIG_ISDN_CAPI_FCCLASSIC
#undef CONFIG_ISDN_CAPI_ISDN_NT
#undef CONFIG_ISDN_CAPI_ISDN_MICRO
#define CONFIG_ISDN_CAPI_ISDN_NT_MICRO_MODULE 1
#define CONFIG_ISDN_NT_MICRO_BLK_MODULE 1
#define CONFIG_ISDN_NT_MICRO_E1_MODULE 1
#define CONFIG_ISDN_NT_MICRO_STACK_MODULE 1
#define CONFIG_ISDN_NT_MICRO_ISDN_AB_MODULE 1
#undef CONFIG_ISDN_NT_MICRO_DEBUG
#undef CONFIG_ISDN_NT_MICRO_KILL_NT
#undef CONFIG_ISDN_NT_MICRO_NO_BCHANNEL
#undef CONFIG_ISDN_NT_MICRO_FAX
#undef CONFIG_ISDN_NT_MICRO_COMPRESS
#undef CONFIG_ISDN_NT_MICRO_MODEM
#define CONFIG_ISDN_NT_MICRO_DTMF 1
#undef CONFIG_ISDN_NT_MICRO_PLC
#define CONFIG_ISDN_NT_MICRO_VCTRLS 1
#define CONFIG_ISDN_NT_MICRO_VCTRLS_NUMBER 5
#define CONFIG_ISDN_NT_MICRO_FRITZX 1
#undef CONFIG_ISDN_CAPI_ISDN_NT_DECT
#undef CONFIG_ISDN_CAPI_ISDN_NT_PCMLINK
#undef CONFIG_ISDN_CAPI_ISDN_PROFI

/*
 * Active Eicon DIVA Server cards
 */
#undef CONFIG_CAPI_EICON

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#undef CONFIG_INPUT_MOUSEDEV
#undef CONFIG_INPUT_JOYDEV
#undef CONFIG_INPUT_TSDEV
#undef CONFIG_INPUT_EVDEV
#undef CONFIG_INPUT_EVBUG

/*
 * Input Device Drivers
 */
#undef CONFIG_INPUT_KEYBOARD
#undef CONFIG_INPUT_MOUSE
#undef CONFIG_INPUT_JOYSTICK
#undef CONFIG_INPUT_TOUCHSCREEN
#undef CONFIG_INPUT_MISC

/*
 * Hardware I/O ports
 */
#undef CONFIG_SERIO
#undef CONFIG_GAMEPORT

/*
 * Character devices
 */
#undef CONFIG_VT
#undef CONFIG_SERIAL_NONSTANDARD

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#define CONFIG_SERIAL_8250_NR_UARTS 1
#undef CONFIG_SERIAL_8250_EXTENDED

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_LEGACY_PTYS 1
#define CONFIG_LEGACY_PTY_COUNT 16

/*
 * IPMI
 */
#undef CONFIG_IPMI_HANDLER

/*
 * Watchdog Cards
 */
#undef CONFIG_WATCHDOG
#undef CONFIG_RTC
#undef CONFIG_GEN_RTC
#undef CONFIG_DTLK
#undef CONFIG_R3964

/*
 * Ftape, the floppy tape device driver
 */
#undef CONFIG_RAW_DRIVER

/*
 * TPM devices
 */
#define CONFIG_AVM_NET_TRACE 1
#define CONFIG_AVM_POWER 1
#define CONFIG_AVM_POWERMETER 1
#undef CONFIG_AVM_DECT_IO
#define CONFIG_AVM_SAMMEL 1
#define CONFIG_AVM_EVENT 1
#define CONFIG_AVM_PUSH_BUTTON 1
#define CONFIG_AVM_PUSH_BUTTON_GPIO 8
#define CONFIG_AVM_PUSH_BUTTON2 1
#define CONFIG_AVM_PUSH_BUTTON2_GPIO 6
#define CONFIG_AVM_PIGLET_MODULE 1
#define CONFIG_AVM_PIGLET_NOEMIF_MODULE 1
#define CONFIG_AVM_AUDIO_MODULE 1
#define CONFIG_PIGLET_AUDIO_MODULE 1
#define CONFIG_AVM_WATCHDOG 1
#define CONFIG_MIPS_AVALANCHE_LED 1
#define CONFIG_AVM_I2C_MODULE 1
#define CONFIG_AVM_LED 1
#define CONFIG_AVM_LED_OUTPUT_SHIFT_REGISTER 1
#undef CONFIG_AVM_LED_BIER_HOLEN
#define CONFIG_AVM_LED_OUTPUT_SHIFT_REGISTER_MASTER_RESET 12
#define CONFIG_AVM_LED_OUTPUT_SHIFT_REGISTER_SHIFT_CLOCK 13
#define CONFIG_AVM_LED_OUTPUT_SHIFT_REGISTER_STORAGE_CLOCK 10
#define CONFIG_AVM_LED_OUTPUT_SHIFT_REGISTER_DATA 9
#define CONFIG_AVM_LED_OUTPUT_GPIO 1
#define CONFIG_AVM_LED_OUTPUT_DUAL_GPIO 1
#define CONFIG_UBIK2_MODULE 1
#undef CONFIG_PCMROUTE_ONLY
#define CONFIG_AVM_FLASH_UPDATE_MODULE 1
#define CONFIG_TFFS2 1
#define CONFIG_TFFS_ENV 1
#define CONFIG_TFFS_MTD_DEVICE_0 4
#define CONFIG_TFFS_MTD_DEVICE_1 5
#define CONFIG_TFFS_PANIC_LOG 1
#define CONFIG_TFFS_PANIC_LOG_ID 96
#undef CONFIG_AVM_RCAPI

/*
 * I2C support
 */
#undef CONFIG_I2C
#undef CONFIG_I2C_SENSOR

/*
 * SPI support
 */
#undef CONFIG_SPI
#undef CONFIG_SPI_MASTER

/*
 * Dallas's 1-wire bus
 */
#undef CONFIG_W1

/*
 * Hardware Monitoring support
 */
#undef CONFIG_HWMON

/*
 * Misc devices
 */

/*
 * Multimedia devices
 */
#undef CONFIG_VIDEO_DEV

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Graphics support
 */
#undef CONFIG_FB

/*
 * Sound
 */
#undef CONFIG_SOUND

/*
 * USB support
 */
#define CONFIG_USB_ARCH_HAS_HCD 1
#undef CONFIG_USB_ARCH_HAS_OHCI
#define CONFIG_USB_MODULE 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef CONFIG_USB_BANDWIDTH
#undef CONFIG_USB_DYNAMIC_MINORS
#undef CONFIG_USB_OTG

/*
 * USB Host Controller Drivers
 */
#define CONFIG_USB_AHCI_MODULE 1
#undef CONFIG_USB_ISP116X_HCD
#undef CONFIG_USB_SL811_HCD

/*
 * USB Device Class drivers
 */

/*
 * USB Bluetooth TTY can only be used with disabled Bluetooth subsystem
 */
#undef CONFIG_USB_ACM
#define CONFIG_USB_PRINTER_MODULE 1

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support' may also be needed; see USB_STORAGE Help for more information
 */
#define CONFIG_USB_STORAGE_MODULE 1
#undef CONFIG_USB_STORAGE_DEBUG
#undef CONFIG_USB_STORAGE_DATAFAB
#undef CONFIG_USB_STORAGE_FREECOM
#undef CONFIG_USB_STORAGE_DPCM
#undef CONFIG_USB_STORAGE_USBAT
#undef CONFIG_USB_STORAGE_SDDR09
#undef CONFIG_USB_STORAGE_SDDR55
#undef CONFIG_USB_STORAGE_JUMPSHOT

/*
 * USB Input Devices
 */
#undef CONFIG_USB_HID

/*
 * USB HID Boot Protocol drivers
 */
#undef CONFIG_USB_KBD
#undef CONFIG_USB_MOUSE
#undef CONFIG_USB_AIPTEK
#undef CONFIG_USB_WACOM
#undef CONFIG_USB_ACECAD
#undef CONFIG_USB_KBTAB
#undef CONFIG_USB_POWERMATE
#undef CONFIG_USB_MTOUCH
#undef CONFIG_USB_ITMTOUCH
#undef CONFIG_USB_EGALAX
#undef CONFIG_USB_XPAD
#undef CONFIG_USB_ATI_REMOTE
#undef CONFIG_USB_KEYSPAN_REMOTE

/*
 * USB Imaging devices
 */
#undef CONFIG_USB_MDC800
#undef CONFIG_USB_MICROTEK

/*
 * USB Multimedia devices
 */
#undef CONFIG_USB_DABUSB

/*
 * Video4Linux support is needed for USB Multimedia device support
 */

/*
 * USB Network Adapters
 */
#undef CONFIG_USB_CATC
#undef CONFIG_USB_KAWETH
#undef CONFIG_USB_PEGASUS
#undef CONFIG_USB_RTL8150
#undef CONFIG_USB_USBNET
#undef CONFIG_USB_ZD1201
#define CONFIG_USB_MON 1

/*
 * USB port drivers
 */

/*
 * USB Serial Converter support
 */
#define CONFIG_USB_SERIAL_MODULE 1
#define CONFIG_USB_SERIAL_GENERIC 1
#undef CONFIG_USB_SERIAL_AIRPRIME
#undef CONFIG_USB_SERIAL_BELKIN
#undef CONFIG_USB_SERIAL_WHITEHEAT
#undef CONFIG_USB_SERIAL_DIGI_ACCELEPORT
#undef CONFIG_USB_SERIAL_CP2101
#undef CONFIG_USB_SERIAL_CYPRESS_M8
#undef CONFIG_USB_SERIAL_EMPEG
#define CONFIG_USB_SERIAL_FTDI_SIO_MODULE 1
#undef CONFIG_USB_SERIAL_VISOR
#undef CONFIG_USB_SERIAL_IPAQ
#undef CONFIG_USB_SERIAL_IR
#undef CONFIG_USB_SERIAL_EDGEPORT
#undef CONFIG_USB_SERIAL_EDGEPORT_TI
#undef CONFIG_USB_SERIAL_GARMIN
#undef CONFIG_USB_SERIAL_IPW
#undef CONFIG_USB_SERIAL_KEYSPAN_PDA
#undef CONFIG_USB_SERIAL_KEYSPAN
#undef CONFIG_USB_SERIAL_KLSI
#undef CONFIG_USB_SERIAL_KOBIL_SCT
#undef CONFIG_USB_SERIAL_MCT_U232
#define CONFIG_USB_SERIAL_PL2303_MODULE 1
#undef CONFIG_USB_SERIAL_HP4X
#undef CONFIG_USB_SERIAL_SAFE
#undef CONFIG_USB_SERIAL_TI
#undef CONFIG_USB_SERIAL_CYBERJACK
#undef CONFIG_USB_SERIAL_XIRCOM
#undef CONFIG_USB_SERIAL_OMNINET

/*
 * USB Miscellaneous drivers
 */
#undef CONFIG_USB_EMI62
#undef CONFIG_USB_EMI26
#undef CONFIG_USB_AUERSWALD
#undef CONFIG_USB_RIO500
#undef CONFIG_USB_LEGOTOWER
#undef CONFIG_USB_LCD
#undef CONFIG_USB_LED
#undef CONFIG_USB_CYTHERM
#undef CONFIG_USB_PHIDGETKIT
#undef CONFIG_USB_PHIDGETSERVO
#undef CONFIG_USB_IDMOUSE
#define CONFIG_USB_AUTH_MODULE 1
#undef CONFIG_USB_LD
#undef CONFIG_USB_TEST

/*
 * USB DSL modem support
 */
#undef CONFIG_USB_ATM

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * MMC/SD Card support
 */
#undef CONFIG_MMC

/*
 * InfiniBand support
 */

/*
 * SN Devices
 */

/*
 * AVM UR8 DSL support
 */

/*
 * File systems
 */

/*
 * YFFS support
 */
#undef CONFIG_YFFS_FS
#undef CONFIG_NANDEMUL2K
#define CONFIG_EXT2_FS_MODULE 1
#define CONFIG_EXT2_FS_XATTR 1
#undef CONFIG_EXT2_FS_POSIX_ACL
#undef CONFIG_EXT2_FS_SECURITY
#undef CONFIG_EXT2_FS_XIP
#define CONFIG_EXT3_FS_MODULE 1
#define CONFIG_EXT3_FS_XATTR 1
#undef CONFIG_EXT3_FS_POSIX_ACL
#undef CONFIG_EXT3_FS_SECURITY
#define CONFIG_JBD_MODULE 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE_MODULE 1
#define CONFIG_REISERFS_FS_MODULE 1
#undef CONFIG_REISERFS_CHECK
#undef CONFIG_REISERFS_PROC_INFO
#undef CONFIG_REISERFS_FS_XATTR
#undef CONFIG_JFS_FS
#undef CONFIG_FS_POSIX_ACL

/*
 * XFS support
 */
#undef CONFIG_XFS_FS
#define CONFIG_MINI_FO_MODULE 1
#undef CONFIG_MINIX_FS
#undef CONFIG_ROMFS_FS
#define CONFIG_INOTIFY 1
#undef CONFIG_QUOTA
#undef CONFIG_DNOTIFY
#undef CONFIG_AUTOFS_FS
#undef CONFIG_AUTOFS4_FS

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS_MODULE 1
#define CONFIG_JOLIET 1
#undef CONFIG_ZISOFS
#define CONFIG_UDF_FS_MODULE 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS_MODULE 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS_MODULE 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#define CONFIG_DEVPTS_FS_XATTR 1
#undef CONFIG_DEVPTS_FS_SECURITY
#define CONFIG_TMPFS 1
#undef CONFIG_TMPFS_XATTR
#undef CONFIG_HUGETLB_PAGE
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#undef CONFIG_HFS_FS
#undef CONFIG_HFSPLUS_FS
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#undef CONFIG_EFS_FS
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS_MODULE 1
#define CONFIG_JFFS2_FS_DEBUG 0
#define CONFIG_JFFS2_FS_WRITEBUFFER 1
#undef CONFIG_JFFS2_COMPRESSION_OPTIONS
#define CONFIG_JFFS2_ZLIB 1
#define CONFIG_JFFS2_RTIME 1
#undef CONFIG_JFFS2_RUBIN
#undef CONFIG_CRAMFS
#define CONFIG_SQUASHFS 1
#define CONFIG_SQUASHFS_EMBEDDED 1
#define CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE 3
#define CONFIG_SQUASHFS_VMALLOC 1
#undef CONFIG_VXFS_FS
#undef CONFIG_HPFS_FS
#undef CONFIG_QNX4FS_FS
#undef CONFIG_SYSV_FS
#undef CONFIG_UFS_FS
#define CONFIG_UNION_FS_MODULE 1

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#undef CONFIG_NFS_V3_ACL
#undef CONFIG_NFS_V4
#undef CONFIG_NFS_DIRECTIO
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#undef CONFIG_NFSD_V3_ACL
#undef CONFIG_NFSD_V4
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_NFS_COMMON 1
#define CONFIG_SUNRPC_MODULE 1
#undef CONFIG_RPCSEC_GSS_KRB5
#undef CONFIG_RPCSEC_GSS_SPKM3
#define CONFIG_SMB_FS_MODULE 1
#undef CONFIG_SMB_NLS_DEFAULT
#define CONFIG_CIFS_MODULE 1
#undef CONFIG_CIFS_STATS
#undef CONFIG_CIFS_XATTR
#undef CONFIG_CIFS_EXPERIMENTAL
#undef CONFIG_NCP_FS
#define CONFIG_CODA_FS_MODULE 1
#undef CONFIG_CODA_FS_OLD_API
#undef CONFIG_AFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_ACORN_PARTITION
#undef CONFIG_OSF_PARTITION
#undef CONFIG_AMIGA_PARTITION
#undef CONFIG_ATARI_PARTITION
#undef CONFIG_MAC_PARTITION
#define CONFIG_MSDOS_PARTITION 1
#undef CONFIG_BSD_DISKLABEL
#undef CONFIG_MINIX_SUBPARTITION
#undef CONFIG_SOLARIS_X86_PARTITION
#undef CONFIG_UNIXWARE_DISKLABEL
#undef CONFIG_LDM_PARTITION
#undef CONFIG_SGI_PARTITION
#undef CONFIG_ULTRIX_PARTITION
#undef CONFIG_SUN_PARTITION
#undef CONFIG_EFI_PARTITION

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#undef CONFIG_NLS_CODEPAGE_737
#undef CONFIG_NLS_CODEPAGE_775
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#undef CONFIG_NLS_CODEPAGE_852
#undef CONFIG_NLS_CODEPAGE_855
#undef CONFIG_NLS_CODEPAGE_857
#undef CONFIG_NLS_CODEPAGE_860
#undef CONFIG_NLS_CODEPAGE_861
#undef CONFIG_NLS_CODEPAGE_862
#undef CONFIG_NLS_CODEPAGE_863
#undef CONFIG_NLS_CODEPAGE_864
#undef CONFIG_NLS_CODEPAGE_865
#undef CONFIG_NLS_CODEPAGE_866
#undef CONFIG_NLS_CODEPAGE_869
#undef CONFIG_NLS_CODEPAGE_936
#undef CONFIG_NLS_CODEPAGE_950
#undef CONFIG_NLS_CODEPAGE_932
#undef CONFIG_NLS_CODEPAGE_949
#undef CONFIG_NLS_CODEPAGE_874
#undef CONFIG_NLS_ISO8859_8
#undef CONFIG_NLS_CODEPAGE_1250
#undef CONFIG_NLS_CODEPAGE_1251
#undef CONFIG_NLS_ASCII
#define CONFIG_NLS_ISO8859_1_MODULE 1
#undef CONFIG_NLS_ISO8859_2
#undef CONFIG_NLS_ISO8859_3
#undef CONFIG_NLS_ISO8859_4
#undef CONFIG_NLS_ISO8859_5
#undef CONFIG_NLS_ISO8859_6
#undef CONFIG_NLS_ISO8859_7
#undef CONFIG_NLS_ISO8859_9
#undef CONFIG_NLS_ISO8859_13
#undef CONFIG_NLS_ISO8859_14
#define CONFIG_NLS_ISO8859_15_MODULE 1
#undef CONFIG_NLS_KOI8_R
#undef CONFIG_NLS_KOI8_U
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Kernel hacking
 */
#undef CONFIG_PRINTK_TIME
#define CONFIG_DEBUG_KERNEL 1
#define CONFIG_MAGIC_SYSRQ 1
#define CONFIG_LOG_BUF_SHIFT 15
#define CONFIG_SCHEDSTATS 1
#undef CONFIG_DEBUG_SLAB
#undef CONFIG_DEBUG_SPINLOCK
#undef CONFIG_DEBUG_SPINLOCK_SLEEP
#undef CONFIG_DEBUG_KOBJECT
#undef CONFIG_DEBUG_INFO
#undef CONFIG_DEBUG_FS
#define CONFIG_CROSSCOMPILE 1
#define CONFIG_CMDLINE ""
#undef CONFIG_DEBUG_STACK_USAGE
#undef CONFIG_KGDB
#undef CONFIG_RUNTIME_DEBUG
#undef CONFIG_MIPS_UNCACHED

/*
 * Security options
 */
#undef CONFIG_KEYS
#undef CONFIG_SECURITY

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#undef CONFIG_CRYPTO_HMAC
#undef CONFIG_CRYPTO_NULL
#undef CONFIG_CRYPTO_MD4
#undef CONFIG_CRYPTO_MD5
#define CONFIG_CRYPTO_SHA1_MODULE 1
#define CONFIG_CRYPTO_SHA256_MODULE 1
#undef CONFIG_CRYPTO_SHA512
#undef CONFIG_CRYPTO_WP512
#undef CONFIG_CRYPTO_TGR192
#undef CONFIG_CRYPTO_DES
#undef CONFIG_CRYPTO_BLOWFISH
#undef CONFIG_CRYPTO_TWOFISH
#undef CONFIG_CRYPTO_SERPENT
#define CONFIG_CRYPTO_AES_MODULE 1
#undef CONFIG_CRYPTO_CAST5
#undef CONFIG_CRYPTO_CAST6
#undef CONFIG_CRYPTO_TEA
#define CONFIG_CRYPTO_ARC4_MODULE 1
#undef CONFIG_CRYPTO_KHAZAD
#undef CONFIG_CRYPTO_ANUBIS
#undef CONFIG_CRYPTO_DEFLATE
#undef CONFIG_CRYPTO_MICHAEL_MIC
#undef CONFIG_CRYPTO_CRC32C
#undef CONFIG_CRYPTO_TEST

/*
 * Hardware crypto devices
 */

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT_MODULE 1
#define CONFIG_CRC32 1
#undef CONFIG_LIBCRC32C
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1
#define CONFIG_GENERIC_HARDIRQS 1
#define CONFIG_GENERIC_IRQ_PROBE 1
#define CONFIG_ISA_DMA_API 1
