// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_util_prefs_FileBasedFactory__
#define __gnu_java_util_prefs_FileBasedFactory__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace util
      {
        namespace prefs
        {
          class FileBasedFactory;
        }
      }
    }
  }
}

class gnu::java::util::prefs::FileBasedFactory : public ::java::lang::Object
{
public:
  virtual ::java::util::prefs::Preferences *systemRoot () { return 0; }
  virtual ::java::util::prefs::Preferences *userRoot () { return 0; }
  FileBasedFactory ();

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_util_prefs_FileBasedFactory__ */
