// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_rmi_rmic_CompilerProcess__
#define __gnu_java_rmi_rmic_CompilerProcess__

#pragma interface

#include <gnu/java/rmi/rmic/Compiler.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace rmi
      {
        namespace rmic
        {
          class CompilerProcess;
        }
      }
    }
  }
}

class gnu::java::rmi::rmic::CompilerProcess : public ::gnu::java::rmi::rmic::Compiler
{
public:
  virtual JArray< ::java::lang::String *> *computeArguments (::java::lang::String *) = 0;
  static JArray< ::java::lang::String *> *computeTypicalArguments (JArray< ::java::lang::String *> *, ::java::lang::String *, ::java::lang::String *);
  virtual void compile (::java::lang::String *);
  CompilerProcess ();

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_rmi_rmic_CompilerProcess__ */
