// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_table_DefaultTableCellRenderer__
#define __javax_swing_table_DefaultTableCellRenderer__

#pragma interface

#include <javax/swing/JLabel.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Component;
    }
  }
  namespace javax
  {
    namespace swing
    {
      namespace table
      {
        class DefaultTableCellRenderer;
      }
      class JTable;
    }
  }
}

class javax::swing::table::DefaultTableCellRenderer : public ::javax::swing::JLabel
{
public:
  DefaultTableCellRenderer ();
  virtual ::java::awt::Component *getTableCellRendererComponent (::javax::swing::JTable *, ::java::lang::Object *, jboolean, jboolean, jint, jint) { return 0; }
public: // actually package-private
  static const jlong serialVersionUID = 7878911414715528324LL;

  friend class javax_swing_table_DefaultTableCellRenderer$UIResource;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_table_DefaultTableCellRenderer__ */
