// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_print_attribute_DocAttributeSet__
#define __javax_print_attribute_DocAttributeSet__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace print
    {
      namespace attribute
      {
        class DocAttributeSet;
        class AttributeSet;
        class Attribute;
      }
    }
  }
}

class javax::print::attribute::DocAttributeSet : public ::java::lang::Object
{
public:
  virtual jboolean add (::javax::print::attribute::Attribute *) = 0;
  virtual jboolean addAll (::javax::print::attribute::AttributeSet *) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_print_attribute_DocAttributeSet__ */
