// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_print_attribute_SupportedValuesAttribute__
#define __javax_print_attribute_SupportedValuesAttribute__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace print
    {
      namespace attribute
      {
        class SupportedValuesAttribute;
      }
    }
  }
}

class javax::print::attribute::SupportedValuesAttribute : public ::java::lang::Object
{
public:

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_print_attribute_SupportedValuesAttribute__ */
