// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_naming_InterruptedNamingException__
#define __javax_naming_InterruptedNamingException__

#pragma interface

#include <javax/naming/NamingException.h>

extern "Java"
{
  namespace javax
  {
    namespace naming
    {
      class InterruptedNamingException;
    }
  }
}

class javax::naming::InterruptedNamingException : public ::javax::naming::NamingException
{
public:
  InterruptedNamingException ();
  InterruptedNamingException (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_naming_InterruptedNamingException__ */
