// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_naming_PartialResultException__
#define __javax_naming_PartialResultException__

#pragma interface

#include <javax/naming/NamingException.h>

extern "Java"
{
  namespace javax
  {
    namespace naming
    {
      class PartialResultException;
    }
  }
}

class javax::naming::PartialResultException : public ::javax::naming::NamingException
{
public:
  PartialResultException ();
  PartialResultException (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_naming_PartialResultException__ */
