// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_naming_TimeLimitExceededException__
#define __javax_naming_TimeLimitExceededException__

#pragma interface

#include <javax/naming/LimitExceededException.h>

extern "Java"
{
  namespace javax
  {
    namespace naming
    {
      class TimeLimitExceededException;
    }
  }
}

class javax::naming::TimeLimitExceededException : public ::javax::naming::LimitExceededException
{
public:
  TimeLimitExceededException ();
  TimeLimitExceededException (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_naming_TimeLimitExceededException__ */
