// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_reflect_Constructor__
#define __java_lang_reflect_Constructor__

#pragma interface

#include <java/lang/reflect/AccessibleObject.h>
#include <gcj/array.h>

class java::lang::reflect::Constructor : public ::java::lang::reflect::AccessibleObject
{
private:
  Constructor ();
public:
  ::java::lang::Class *getDeclaringClass () { return declaringClass; }
  ::java::lang::String *getName ();
  jint getModifiers ();
  JArray< ::java::lang::Class *> *getParameterTypes ();
  JArray< ::java::lang::Class *> *getExceptionTypes ();
  jboolean equals (::java::lang::Object *);
  jint hashCode ();
  ::java::lang::String *toString ();
  ::java::lang::Object *newInstance (JArray< ::java::lang::Object *> *);
private:
  void getType ();
  ::java::lang::Class * __attribute__((aligned(__alignof__( ::java::lang::reflect::AccessibleObject )))) declaringClass;
  JArray< ::java::lang::Class *> *exception_types;
  JArray< ::java::lang::Class *> *parameter_types;
  jint offset;
  friend jmethodID _Jv_FromReflectedConstructor (java::lang::reflect::Constructor *);
  friend class java::lang::Class;
  friend jobject _Jv_JNI_ToReflectedMethod (_Jv_JNIEnv *, jclass, jmethodID, jboolean);
public:

  static ::java::lang::Class class$;
};

#endif /* __java_lang_reflect_Constructor__ */
