// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_util_logging_FileHandler__
#define __java_util_logging_FileHandler__

#pragma interface

#include <java/util/logging/StreamHandler.h>

class java::util::logging::FileHandler : public ::java::util::logging::StreamHandler
{
public:
  FileHandler ();
  FileHandler (::java::lang::String *);
  FileHandler (::java::lang::String *, jboolean);
  FileHandler (::java::lang::String *, jint, jint);
  FileHandler (::java::lang::String *, jint, jint, jboolean);
private:
  static ::java::io::OutputStream *createFileStream (::java::lang::String *, jint, jint, jboolean, jint);
  static ::java::lang::String *replaceFileNameEscapes (::java::lang::String *, jint, jint, jint);
public:
  virtual void publish (::java::util::logging::LogRecord *);
private:
  jint __attribute__((aligned(__alignof__( ::java::util::logging::StreamHandler ))))  limit;
  jint count;
  ::java::lang::String *pattern;
  jboolean append;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_util_logging_FileHandler__ */
