// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_awt_datatransfer_SystemFlavorMap__
#define __java_awt_datatransfer_SystemFlavorMap__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      namespace datatransfer
      {
        class SystemFlavorMap;
        class DataFlavor;
        class FlavorMap;
      }
    }
  }
}

class java::awt::datatransfer::SystemFlavorMap : public ::java::lang::Object
{
private:
  SystemFlavorMap ();
public:
  ::java::util::Map *getNativesForFlavors (JArray< ::java::awt::datatransfer::DataFlavor *> *);
  ::java::util::Map *getFlavorsForNatives (JArray< ::java::lang::String *> *);
  static ::java::awt::datatransfer::FlavorMap *getDefaultFlavorMap ();
  static ::java::lang::String *encodeJavaMIMEType (::java::lang::String *) { return 0; }
  static ::java::lang::String *encodeDataFlavor (::java::awt::datatransfer::DataFlavor *) { return 0; }
  static jboolean isJavaMIMEType (::java::lang::String *);
  static ::java::lang::String *decodeJavaMIMEType (::java::lang::String *) { return 0; }
  static ::java::awt::datatransfer::DataFlavor *decodeDataFlavor (::java::lang::String *);
  ::java::util::List *getFlavorsForNative (::java::lang::String *);
  ::java::util::List *getNativesForFlavor (::java::awt::datatransfer::DataFlavor *);
private:
  static ::java::awt::datatransfer::FlavorMap *defaultFlavorMap;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_awt_datatransfer_SystemFlavorMap__ */
