// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JCheckBox__
#define __javax_swing_JCheckBox__

#pragma interface

#include <javax/swing/JToggleButton.h>

extern "Java"
{
  namespace javax
  {
    namespace accessibility
    {
      class AccessibleContext;
    }
    namespace swing
    {
      class JCheckBox;
      class Icon;
      class Action;
    }
  }
}

class javax::swing::JCheckBox : public ::javax::swing::JToggleButton
{
public:
  JCheckBox ();
  JCheckBox (::javax::swing::Action *);
  JCheckBox (::javax::swing::Icon *);
  JCheckBox (::java::lang::String *);
  JCheckBox (::java::lang::String *, ::javax::swing::Icon *);
  virtual ::javax::accessibility::AccessibleContext *getAccessibleContext () { return 0; }
  virtual ::java::lang::String *getUIClassID ();
public:  // actually protected
  virtual ::java::lang::String *paramString ();
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JCheckBox__ */
