// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JCheckBoxMenuItem__
#define __javax_swing_JCheckBoxMenuItem__

#pragma interface

#include <javax/swing/JMenuItem.h>
#include <gcj/array.h>

extern "Java"
{
  namespace javax
  {
    namespace accessibility
    {
      class AccessibleContext;
    }
    namespace swing
    {
      class JCheckBoxMenuItem;
      class Action;
      class Icon;
    }
  }
}

class javax::swing::JCheckBoxMenuItem : public ::javax::swing::JMenuItem
{
public:
  JCheckBoxMenuItem ();
  JCheckBoxMenuItem (::javax::swing::Icon *);
  JCheckBoxMenuItem (::java::lang::String *);
  JCheckBoxMenuItem (::javax::swing::Action *);
  JCheckBoxMenuItem (::java::lang::String *, ::javax::swing::Icon *);
  JCheckBoxMenuItem (::java::lang::String *, jboolean);
  JCheckBoxMenuItem (::java::lang::String *, ::javax::swing::Icon *, jboolean);
private:
  void writeObject (::java::io::ObjectOutputStream *) { }
public:
  virtual ::java::lang::String *getUIClassID ();
  virtual jboolean getState ();
  virtual void setState (jboolean);
  virtual JArray< ::java::lang::Object *> *getSelectedObjects () { return 0; }
  virtual void requestFocus () { }
public:  // actually protected
  virtual ::java::lang::String *paramString () { return 0; }
public:
  virtual ::javax::accessibility::AccessibleContext *getAccessibleContext ();
private:
  static ::java::lang::String *uiClassID;

  friend class javax_swing_JCheckBoxMenuItem$AccessibleJCheckBoxMenuItem;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JCheckBoxMenuItem__ */
