// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JFrame__
#define __javax_swing_JFrame__

#pragma interface

#include <java/awt/Frame.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      namespace event
      {
        class WindowEvent;
        class KeyEvent;
      }
      class Graphics;
      class Component;
      class Container;
      class LayoutManager;
      class Dimension;
    }
  }
  namespace javax
  {
    namespace swing
    {
      class JFrame;
      class JLayeredPane;
      class JMenuBar;
      class JRootPane;
    }
    namespace accessibility
    {
      class AccessibleContext;
    }
  }
}

class javax::swing::JFrame : public ::java::awt::Frame
{
public:
  JFrame ();
  JFrame (::java::lang::String *);
public:  // actually protected
  virtual void frameInit ();
public:
  virtual ::java::awt::Dimension *getPreferredSize ();
public: // actually package-private
  virtual ::javax::swing::JMenuBar *getJMenuBar ();
  virtual void setJMenuBar (::javax::swing::JMenuBar *);
public:
  virtual void setLayout (::java::awt::LayoutManager *);
public: // actually package-private
  virtual void setLayeredPane (::javax::swing::JLayeredPane *);
  virtual ::javax::swing::JLayeredPane *getLayeredPane ();
  virtual ::javax::swing::JRootPane *getRootPane ();
  virtual void setRootPane (::javax::swing::JRootPane *);
  virtual ::javax::swing::JRootPane *createRootPane ();
public:
  virtual ::java::awt::Container *getContentPane ();
public: // actually package-private
  virtual void setContentPane (::java::awt::Container *);
  virtual ::java::awt::Component *getGlassPane ();
  virtual void setGlassPane (::java::awt::Component *);
public:  // actually protected
  virtual void addImpl (::java::awt::Component *, ::java::lang::Object *, jint);
public:
  virtual void remove (::java::awt::Component *);
public:  // actually protected
  virtual jboolean isRootPaneCheckingEnabled () { return checking; }
  virtual void setRootPaneCheckingEnabled (jboolean);
public:
  virtual void update (::java::awt::Graphics *);
public:  // actually protected
  virtual void processKeyEvent (::java::awt::event::KeyEvent *);
public:
  virtual ::javax::accessibility::AccessibleContext *getAccessibleContext () { return accessibleContext; }
public: // actually package-private
  virtual jint getDefaultCloseOperation () { return close_action; }
public:  // actually protected
  virtual ::java::lang::String *paramString ();
  virtual void processWindowEvent (::java::awt::event::WindowEvent *);
public: // actually package-private
  virtual void setDefaultCloseOperation (jint);
public:
  static const jint HIDE_ON_CLOSE = 0L;
  static const jint EXIT_ON_CLOSE = 1L;
  static const jint DISPOSE_ON_CLOSE = 2L;
  static const jint DO_NOTHING_ON_CLOSE = 3L;
public:  // actually protected
  ::javax::accessibility::AccessibleContext * __attribute__((aligned(__alignof__( ::java::awt::Frame )))) accessibleContext;
private:
  jint close_action;
  jboolean checking;
public:  // actually protected
  ::javax::swing::JRootPane *rootPane;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JFrame__ */
