// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JProgressBar__
#define __javax_swing_JProgressBar__

#pragma interface

#include <javax/swing/JComponent.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      class Graphics;
    }
  }
  namespace javax
  {
    namespace accessibility
    {
      class AccessibleContext;
    }
    namespace swing
    {
      class JProgressBar;
      namespace plaf
      {
        class ProgressBarUI;
      }
      namespace event
      {
        class ChangeListener;
        class ChangeEvent;
      }
      class BoundedRangeModel;
    }
  }
}

class javax::swing::JProgressBar : public ::javax::swing::JComponent
{
public:
  JProgressBar ();
  JProgressBar (jint);
  JProgressBar (jint, jint);
  JProgressBar (jint, jint, jint);
  JProgressBar (::javax::swing::BoundedRangeModel *);
private:
  void writeObject (::java::io::ObjectOutputStream *) { }
public:
  virtual jint getValue ();
  virtual void setValue (jint) { }
public:  // actually protected
  virtual void paintBorder (::java::awt::Graphics *) { }
public:
  virtual jint getOrientation ();
  virtual void setOrientation (jint) { }
  virtual jboolean isStringPainted ();
  virtual void setStringPainted (jboolean) { }
  virtual ::java::lang::String *getString () { return 0; }
  virtual void setString (::java::lang::String *) { }
  virtual jdouble getPercentComplete ();
  virtual jboolean isBorderPainted ();
  virtual void setBorderPainted (jboolean) { }
  virtual ::javax::swing::plaf::ProgressBarUI *getUI ();
  virtual void setUI (::javax::swing::plaf::ProgressBarUI *);
  virtual void updateUI ();
  virtual ::java::lang::String *getUIClassID ();
public:  // actually protected
  virtual ::javax::swing::event::ChangeListener *createChangeListener () { return 0; }
public:
  virtual void addChangeListener (::javax::swing::event::ChangeListener *) { }
  virtual void removeChangeListener (::javax::swing::event::ChangeListener *) { }
public:  // actually protected
  virtual void fireStateChanged () { }
public:
  virtual ::javax::swing::BoundedRangeModel *getModel () { return 0; }
  virtual void setModel (::javax::swing::BoundedRangeModel *) { }
  virtual jint getMinimum ();
  virtual void setMinimum (jint) { }
  virtual jint getMaximum ();
  virtual void setMaximum (jint) { }
public:  // actually protected
  virtual ::java::lang::String *paramString () { return 0; }
public:
  virtual ::javax::accessibility::AccessibleContext *getAccessibleContext ();
private:
  static ::java::lang::String *uiClassID;
public:  // actually protected
  jint __attribute__((aligned(__alignof__( ::javax::swing::JComponent ))))  orientation;
  jboolean paintBorder__;
  ::javax::swing::BoundedRangeModel *model;
  ::java::lang::String *progressString;
  jboolean paintString;
  ::javax::swing::event::ChangeEvent *changeEvent;
  ::javax::swing::event::ChangeListener *changeListener;

  friend class javax_swing_JProgressBar$AccessibleJProgressBar;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JProgressBar__ */
