// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JSplitPane__
#define __javax_swing_JSplitPane__

#pragma interface

#include <javax/swing/JComponent.h>

extern "Java"
{
  namespace javax
  {
    namespace accessibility
    {
      class AccessibleContext;
    }
    namespace swing
    {
      class JSplitPane;
      namespace plaf
      {
        class SplitPaneUI;
      }
    }
  }
  namespace java
  {
    namespace awt
    {
      class Graphics;
      class Component;
    }
  }
}

class javax::swing::JSplitPane : public ::javax::swing::JComponent
{
public:
  JSplitPane ();
  JSplitPane (jint);
  JSplitPane (jint, jboolean);
  JSplitPane (jint, ::java::awt::Component *, ::java::awt::Component *);
  JSplitPane (jint, jboolean, ::java::awt::Component *, ::java::awt::Component *);
private:
  void writeObject (::java::io::ObjectOutputStream *) { }
public:
  virtual void remove (::java::awt::Component *) { }
  virtual void remove (jint) { }
  virtual void removeAll () { }
  virtual void setUI (::javax::swing::plaf::SplitPaneUI *);
  virtual ::javax::swing::plaf::SplitPaneUI *getUI ();
  virtual void updateUI ();
  virtual ::java::lang::String *getUIClassID ();
  virtual void setDividerSize (jint) { }
  virtual jint getDividerSize ();
  virtual void setLeftComponent (::java::awt::Component *) { }
  virtual ::java::awt::Component *getLeftComponent () { return 0; }
  virtual void setTopComponent (::java::awt::Component *) { }
  virtual ::java::awt::Component *getTopComponent () { return 0; }
  virtual void setRightComponent (::java::awt::Component *) { }
  virtual ::java::awt::Component *getRightComponent () { return 0; }
  virtual void setBottomComponent (::java::awt::Component *) { }
  virtual ::java::awt::Component *getBottomComponent () { return 0; }
  virtual void setOneTouchExpandable (jboolean) { }
  virtual jboolean isOneTouchExpandable ();
  virtual void setLastDividerLocation (jint) { }
  virtual jint getLastDividerLocation ();
  virtual void setOrientation (jint) { }
  virtual jint getOrientation ();
  virtual void setContinuousLayout (jboolean) { }
  virtual jboolean isContinuousLayout ();
  virtual void setResizeWeight (jdouble) { }
  virtual jdouble getResizeWeight ();
  virtual void resetToPreferredSizes () { }
  virtual void setDividerLocation (jdouble) { }
  virtual void setDividerLocation (jint) { }
  virtual jint getDividerLocation ();
  virtual jint getMinimumDividerLocation ();
  virtual jint getMaximumDividerLocation ();
  virtual jboolean isValidateRoot ();
public:  // actually protected
  virtual void addImpl (::java::awt::Component *, ::java::lang::Object *, jint) { }
  virtual void paintChildren (::java::awt::Graphics *) { }
  virtual ::java::lang::String *paramString () { return 0; }
public:
  virtual ::javax::accessibility::AccessibleContext *getAccessibleContext ();
private:
  static ::java::lang::String *uiClassID;
public:
  static const jint VERTICAL_SPLIT = 0L;
  static const jint HORIZONTAL_SPLIT = 1L;
  static ::java::lang::String *LEFT;
  static ::java::lang::String *RIGHT;
  static ::java::lang::String *TOP;
  static ::java::lang::String *BOTTOM;
  static ::java::lang::String *DIVIDER;
  static ::java::lang::String *ORIENTATION_PROPERTY;
  static ::java::lang::String *CONTINUOUS_LAYOUT_PROPERTY;
  static ::java::lang::String *DIVIDER_SIZE_PROPERTY;
  static ::java::lang::String *ONE_TOUCH_EXPANDABLE_PROPERTY;
  static ::java::lang::String *LAST_DIVIDER_LOCATION_PROPERTY;
  static ::java::lang::String *DIVIDER_LOCATION_PROPERTY;
  static ::java::lang::String *RESIZE_WEIGHT_PROPERTY;
public:  // actually protected
  jint __attribute__((aligned(__alignof__( ::javax::swing::JComponent ))))  orientation;
  jboolean continuousLayout;
  ::java::awt::Component *leftComponent;
  ::java::awt::Component *rightComponent;
  jint dividerSize;
  jboolean oneTouchExpandable;
  jint lastDividerLocation;
private:
  jdouble resizeWeight;
  jint dividerLocation;

  friend class javax_swing_JSplitPane$AccessibleJSplitPane;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JSplitPane__ */
