// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JToolTip__
#define __javax_swing_JToolTip__

#pragma interface

#include <javax/swing/JComponent.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      class JToolTip;
    }
  }
}

class javax::swing::JToolTip : public ::javax::swing::JComponent
{
public: // actually package-private
  JToolTip (::java::lang::String *);
  ::java::lang::String * __attribute__((aligned(__alignof__( ::javax::swing::JComponent )))) text;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_swing_JToolTip__ */
