// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_io_DataOutputStream__
#define __java_io_DataOutputStream__

#pragma interface

#include <java/io/FilterOutputStream.h>
#include <gcj/array.h>

class java::io::DataOutputStream : public ::java::io::FilterOutputStream
{
public:
  DataOutputStream (::java::io::OutputStream *);
  virtual void flush ();
  jint size () { return written; }
  virtual void write (jint);
  virtual void write (jbyteArray, jint, jint);
  void writeBoolean (jboolean);
  void writeByte (jint);
  void writeShort (jint);
  void writeChar (jint);
  void writeInt (jint);
  void writeLong (jlong);
  void writeFloat (jfloat);
  void writeDouble (jdouble);
  void writeBytes (::java::lang::String *);
  void writeChars (::java::lang::String *);
  void writeUTF (::java::lang::String *);
public:  // actually protected
  jint __attribute__((aligned(__alignof__( ::java::io::FilterOutputStream ))))  written;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_io_DataOutputStream__ */
