// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_sql_RowSet__
#define __javax_sql_RowSet__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace javax
  {
    namespace sql
    {
      class RowSet;
      class RowSetListener;
    }
  }
  namespace java
  {
    namespace sql
    {
      class Array;
      class Clob;
      class Blob;
      class Ref;
      class Timestamp;
      class Time;
      class Date;
    }
    namespace math
    {
      class BigDecimal;
    }
  }
}

class javax::sql::RowSet : public ::java::lang::Object
{
public:
  virtual ::java::lang::String *getUrl () = 0;
  virtual void setUrl (::java::lang::String *) = 0;
  virtual ::java::lang::String *getDataSourceName () = 0;
  virtual void setDataSourceName (::java::lang::String *) = 0;
  virtual ::java::lang::String *getUsername () = 0;
  virtual void setUsername (::java::lang::String *) = 0;
  virtual ::java::lang::String *getPassword () = 0;
  virtual void setPassword (::java::lang::String *) = 0;
  virtual jint getTransactionIsolation () = 0;
  virtual void setTransactionIsolation (jint) = 0;
  virtual ::java::util::Map *getTypeMap () = 0;
  virtual void setTypeMap (::java::util::Map *) = 0;
  virtual ::java::lang::String *getCommand () = 0;
  virtual void setCommand (::java::lang::String *) = 0;
  virtual jboolean isReadOnly () = 0;
  virtual void setReadOnly (jboolean) = 0;
  virtual jint getMaxFieldSize () = 0;
  virtual void setMaxFieldSize (jint) = 0;
  virtual jint getMaxRows () = 0;
  virtual void setMaxRows (jint) = 0;
  virtual jboolean getEscapeProcessing () = 0;
  virtual void setEscapeProcessing (jboolean) = 0;
  virtual jint getQueryTimeout () = 0;
  virtual void setQueryTimeout (jint) = 0;
  virtual void setType (jint) = 0;
  virtual void setConcurrency (jint) = 0;
  virtual void setNull (jint, jint) = 0;
  virtual void setNull (jint, jint, ::java::lang::String *) = 0;
  virtual void setBoolean (jint, jboolean) = 0;
  virtual void setByte (jint, jbyte) = 0;
  virtual void setShort (jint, jshort) = 0;
  virtual void setInt (jint, jint) = 0;
  virtual void setLong (jint, jlong) = 0;
  virtual void setFloat (jint, jfloat) = 0;
  virtual void setDouble (jint, jdouble) = 0;
  virtual void setBigDecimal (jint, ::java::math::BigDecimal *) = 0;
  virtual void setString (jint, ::java::lang::String *) = 0;
  virtual void setBytes (jint, jbyteArray) = 0;
  virtual void setDate (jint, ::java::sql::Date *) = 0;
  virtual void setTime (jint, ::java::sql::Time *) = 0;
  virtual void setTimestamp (jint, ::java::sql::Timestamp *) = 0;
  virtual void setAsciiStream (jint, ::java::io::InputStream *, jint) = 0;
  virtual void setBinaryStream (jint, ::java::io::InputStream *, jint) = 0;
  virtual void setCharacterStream (jint, ::java::io::Reader *, jint) = 0;
  virtual void setObject (jint, ::java::lang::Object *, jint, jint) = 0;
  virtual void setObject (jint, ::java::lang::Object *, jint) = 0;
  virtual void setObject (jint, ::java::lang::Object *) = 0;
  virtual void setRef (jint, ::java::sql::Ref *) = 0;
  virtual void setBlob (jint, ::java::sql::Blob *) = 0;
  virtual void setClob (jint, ::java::sql::Clob *) = 0;
  virtual void setArray (jint, ::java::sql::Array *) = 0;
  virtual void setDate (jint, ::java::sql::Date *, ::java::util::Calendar *) = 0;
  virtual void setTime (jint, ::java::sql::Time *, ::java::util::Calendar *) = 0;
  virtual void setTimestamp (jint, ::java::sql::Timestamp *, ::java::util::Calendar *) = 0;
  virtual void clearParameters () = 0;
  virtual void execute () = 0;
  virtual void addRowSetListener (::javax::sql::RowSetListener *) = 0;
  virtual void removeRowSetListener (::javax::sql::RowSetListener *) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_sql_RowSet__ */
