// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_security_PublicKey__
#define __java_security_PublicKey__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace java
  {
    namespace security
    {
      class PublicKey;
    }
  }
}

class java::security::PublicKey : public ::java::lang::Object
{
public:
  static const jlong serialVersionUID = 7187392471159151072LL;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __java_security_PublicKey__ */
