// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_nio_channels_AsynchronousCloseException__
#define __java_nio_channels_AsynchronousCloseException__

#pragma interface

#include <java/nio/channels/ClosedChannelException.h>

extern "Java"
{
  namespace java
  {
    namespace nio
    {
      namespace channels
      {
        class AsynchronousCloseException;
      }
    }
  }
}

class java::nio::channels::AsynchronousCloseException : public ::java::nio::channels::ClosedChannelException
{
public:
  AsynchronousCloseException ();

  static ::java::lang::Class class$;
};

#endif /* __java_nio_channels_AsynchronousCloseException__ */
