// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_awt_EmbeddedWindowSupport__
#define __gnu_java_awt_EmbeddedWindowSupport__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace awt
      {
        class EmbeddedWindowSupport;
        namespace peer
        {
          class EmbeddedWindowPeer;
        }
        class EmbeddedWindow;
      }
    }
  }
}

class gnu::java::awt::EmbeddedWindowSupport : public ::java::lang::Object
{
public:
  virtual ::gnu::java::awt::peer::EmbeddedWindowPeer *createEmbeddedWindow (::gnu::java::awt::EmbeddedWindow *) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __gnu_java_awt_EmbeddedWindowSupport__ */
